-- MySQL Script generated by MySQL Workbench
-- 2015年06月18日 星期四 17时01分37秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iworks
-- -----------------------------------------------------
-- iworks 数据库

-- -----------------------------------------------------
-- Schema iworks
--
-- iworks 数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iworks` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `iworks` ;

-- -----------------------------------------------------
-- Table `iworks`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iworks`.`school` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '学校名称',
  `address` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL COMMENT '学校地址',
  `type` VARCHAR(45) NULL COMMENT '学校类型',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '学校表';


-- -----------------------------------------------------
-- Table `iworks`.`major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iworks`.`major` (
  `id` INT NOT NULL COMMENT '专业id',
  `name` VARCHAR(45) NULL COMMENT '专业名',
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  `school_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_major_school1_idx` (`school_id` ASC),
  CONSTRAINT `fk_major_school1`
    FOREIGN KEY (`school_id`)
    REFERENCES `iworks`.`school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '专业表';


-- -----------------------------------------------------
-- Table `iworks`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iworks`.`class` (
  `id` INT NOT NULL COMMENT '班级id',
  `year` VARCHAR(45) NULL COMMENT '班级届数',
  `class_num` VARCHAR(45) NULL COMMENT '班级号',
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  `major_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_class_major1_idx` (`major_id` ASC),
  CONSTRAINT `fk_class_major1`
    FOREIGN KEY (`major_id`)
    REFERENCES `iworks`.`major` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '班级表';


-- -----------------------------------------------------
-- Table `iworks`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iworks`.`students` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '真实姓名',
  `email` VARCHAR(45) NULL COMMENT '邮箱',
  `class_id` INT NOT NULL COMMENT '班级id',
  `username` VARCHAR(45) NULL COMMENT '用户名',
  `phone` VARCHAR(45) NULL COMMENT '手机号',
  `password` VARCHAR(45) NULL COMMENT '密码',
  `gender` VARCHAR(45) NULL COMMENT '性别',
  `birthday` VARCHAR(45) NULL COMMENT '生日',
  `student_number` VARCHAR(45) NULL COMMENT '学号',
  `status` VARCHAR(45) NULL COMMENT '用户状态',
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_students_class1_idx` (`class_id` ASC),
  CONSTRAINT `fk_students_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `iworks`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '学生表';


-- -----------------------------------------------------
-- Table `iworks`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iworks`.`teachers` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '真实姓名',
  `username` VARCHAR(45) NULL COMMENT '用户名',
  `email` VARCHAR(45) NULL COMMENT '邮箱',
  `phone` VARCHAR(45) NULL COMMENT '手机号',
  `password` VARCHAR(45) NULL COMMENT '密码',
  `gender` VARCHAR(45) NULL COMMENT '性别',
  `birthday` VARCHAR(45) NULL COMMENT '生日',
  `teacher_num` VARCHAR(45) NULL COMMENT '教师号',
  `status` VARCHAR(45) NULL COMMENT '状态',
  `created_at` VARCHAR(45) NULL COMMENT '创建时间',
  `updated_at` VARCHAR(45) NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '教师表';


-- -----------------------------------------------------
-- Table `iworks`.`students_has_teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iworks`.`students_has_teachers` (
  `student_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  `status` VARCHAR(45) NULL COMMENT '状态',
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`student_id`, `teacher_id`),
  INDEX `fk_student_has_teacher_teacher1_idx` (`teacher_id` ASC),
  INDEX `fk_student_has_teacher_student_idx` (`student_id` ASC),
  CONSTRAINT `fk_student_has_teacher_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `iworks`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_teacher_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `iworks`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '教师学生关系表';


-- -----------------------------------------------------
-- Table `iworks`.`works`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iworks`.`works` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL COMMENT '类型 0 电子作业\n1 纸质作业\n2 文章\n3 资料',
  `name` VARCHAR(45) NULL COMMENT '名称',
  `content` VARCHAR(45) NULL COMMENT '详细描述',
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  `teachers_id` INT NOT NULL COMMENT '创建人',
  `deadline` VARCHAR(45) NULL COMMENT '截至时间',
  `tag` VARCHAR(45) NULL COMMENT '标签',
  `subject` VARCHAR(45) NULL COMMENT '科目类别',
  `view` VARCHAR(45) NULL COMMENT '浏览数',
  `status` VARCHAR(45) NULL COMMENT '状态',
  `fileurl` VARCHAR(45) NULL COMMENT '附件',
  PRIMARY KEY (`id`, `teachers_id`),
  INDEX `fk_works_teachers1_idx` (`teachers_id` ASC),
  CONSTRAINT `fk_works_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `iworks`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '作业表';


-- -----------------------------------------------------
-- Table `iworks`.`students_has_works`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iworks`.`students_has_works` (
  `students_id` INT NOT NULL COMMENT '学生id',
  `works_id` INT NOT NULL COMMENT '作业id',
  `status` VARCHAR(45) NULL COMMENT '状态 0 未认领作业\n1 已认领作业\n2 已完成作业\n3 未完成作业',
  `fileurl` VARCHAR(45) NULL COMMENT '附件地址',
  `created_at` VARCHAR(45) NULL COMMENT '创建时间',
  `updated_at` VARCHAR(45) NULL COMMENT '更新时间',
  PRIMARY KEY (`students_id`, `works_id`),
  INDEX `fk_students_has_works_works1_idx` (`works_id` ASC),
  INDEX `fk_students_has_works_students1_idx` (`students_id` ASC),
  CONSTRAINT `fk_students_has_works_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `iworks`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_works_works1`
    FOREIGN KEY (`works_id`)
    REFERENCES `iworks`.`works` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '学生作业关系表';


-- -----------------------------------------------------
-- Table `iworks`.`teachers_has_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iworks`.`teachers_has_class` (
  `teachers_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL COMMENT '状态',
  PRIMARY KEY (`teachers_id`, `class_id`),
  INDEX `fk_teachers_has_class_class1_idx` (`class_id` ASC),
  INDEX `fk_teachers_has_class_teachers1_idx` (`teachers_id` ASC),
  CONSTRAINT `fk_teachers_has_class_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `iworks`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teachers_has_class_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `iworks`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '教师班级关系表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
